apiVersion:       apps/v1
kind:             Deployment
metadata:
  name:           blueocean-master
  labels:
    app:          blueocean
spec:
  replicas:       1
  selector:
    matchLabels:
      app:        blueocean
  template:
    metadata:
      labels:
        app:      blueocean
    spec:
      containers:
        - name:   proxy
          image:  nginx:1.15.7
          ports:
          - containerPort: 80
        - name:   blueocean
          image:  jenkinsci/blueocean:1.9.0
          ports:
          - containerPort: 8080
